---
title: "importE2data"
author: "Alex Holcombe"
date: "2/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Modified from backwardsLtrsLoadRawData.R

```{r set up functions}

#Loads raw data from MATLAB files for second backwards paper first experiment
require(R.matlab)

GoogleDrivePath<-"." # "Google\ Drive/Backwards\ paper"

#First experiment of second backwards-letters paper. random orientation each trial.
rawDataPath<- file.path(GoogleDrivePath,
                            "Data/RawData/Data")
#raw data path containing .mat file for each subject
rawDataExcludedByMATLABpath<- file.path(rawDataPath, "Excluded")

source(file.path("turnMATintoMeltedDataframe.R"))

readInAllFiles<- function(rawDataPath) {

  files <- dir(path=rawDataPath,pattern='.mat')  #find all data files in this directory
  dfAll<-data.frame()
  for (i in 1:length(files)) { #read in each file
    fileThis<- file.path(rawDataPath,files[i])
    rawDataLoad=tryCatch(
      readMat(fileThis),
      error=function(e) {
        stop( paste0("ERROR reading the file ",fileThis," :",e) )
      } )
    apparentSubjectName <- strsplit(files[i],split="_")[[1]][1]
    subjectName<- rawDataLoad$participantID[[1]]
    if (apparentSubjectName != subjectName) {
      stop( paste0("WARNING apparentSubjectName",apparentSubjectName," from filename does not match subjectName in data structure",subjectName) )
    }
    rawDataLoad$file <- files[i]

    dfThis<- turnMATintoMeltedDataframe(rawDataLoad)

    tryCatch(
      dfAll<-rbind(dfAll,dfThis), #if fail to bind new with old,
      error=function(e) { #Give feedback about how the error happened
        cat(paste0("Tried to merge but error:",e) )
      } )
  }
  return(dfAll)
}
```

```{r read raw data}

E<- readInAllFiles(rawDataPath)
#Calculate the serial position error
E$SPE<- E$respSP - E$targetSP

sanityVisualCheck<-FALSE
if (sanityVisualCheck) {
  library(ggplot2)
  g=ggplot(E, aes(x=SPE))
  #plot data
  g<-g+geom_histogram(binwidth=1)
  g
}

#Excluded subfolder contains Ss Chris excluded for low efficacy
excludedSsPath<- file.path(rawDataPath,"Excluded")

excluded<- readInAllFiles(excludedSsPath)
#Calculate the serial position error
excluded$SPE<- excluded$respSP - excluded$targetSP
```

Sanity visual check that see histogram.
```{r sanity visual check}

sanityVisualCheck<-TRUE
if (sanityVisualCheck) {
  library(ggplot2)
  g=ggplot(excluded, aes(x=SPE))
  #plot data
  g<-g+geom_histogram(binwidth=1)
  show(g)
  
  h<-ggplot(E,aes(x=SPE)) + geom_histogram(binwidth=1)
  show(h)
}

```

Meaning of condition variable
* 1 - upright
* 2 - inverted

Combine excluded and non-excluded (based on old MATLAB anaylsis) participants
```{r combine}

E$excluded<-FALSE
excluded$excluded<-TRUE

backwards2_E1<-rbind(E,excluded)

```

Make condition names more sensible - stream (Left/Right) and orientation (Canonical/Inverted)
```{r}
names(backwards2_E1)[names(backwards2_E1) == 'target'] <-'stream'
names(backwards2_E1)[names(backwards2_E1) == 'condition'] <-'orientation'
backwards2_E1$stream[ backwards2_E1$stream==1 ] <- "Left"
backwards2_E1$stream[ backwards2_E1$stream==2 ] <- "Right"
#mutate condition to Orientation
backwards2_E1$orientation[ backwards2_E1$orientation==1 ] <- "Canonical"
backwards2_E1$orientation[ backwards2_E1$orientation==2 ] <- "Inverted"

```

Save data
```{r}
#save dataframe into proper library data directory
#save(backwards2_E1, file = "data/backwards2E1_rawDataFromMAT.rda", compress="bzip2")
saveRDS(backwards2_E1, file = "Data/backwards2E1_rawDataFromMAT.rda", compress="bzip2")
```

